application:
  title: ROSE
  version: 1.0.0

spring:
  application:
    name: seoul-rose

  security:
    enabled: false

  datasource:
    driverClassName: org.postgresql.Driver
    # jdbcUrl: jdbc:postgresql://203.250.148.52:20516/seoul_genai
    jdbcUrl: jdbc:postgresql://203.250.148.52:20516/seoul_genai
    username: default
    password: default

server:
  port: 8080

naver:
  stt-url: https://naveropenapi.apigw.ntruss.com/recog/v1/stt
  client-id: 2cewgcwp3h
  client-secret: lkZpvu9bhJfS8MErVvVqMSFIWk4ySCma2dJ4C52A

genai:
  base: http://203.250.148.52:27580/genai/

video:
  base: http://203.250.148.52:27575/

http.pool:
  max.total: 200
  defaultMaxPerRoute: 100
  connection.timeout: 50000
  connection.request.timeout: 50000
  read.timeout: 100000
  validate.after.inactivity: 20000
