application:
  title: ROSE
  version: 1.0.0

spring:
  application:
    name: seoul-rose

  security:
    enabled: false

  datasource:
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://203.250.148.52:5432/seoul_genai
    username: defalut
    password: defalut

server:
  port: 8080
